Q2A:
  name: "QuBE OU #1-02"
  type: "quel1-a"
  address: "10.1.0.2"
  adapter: "500202A504YAA"
U7B:
  name: "QuBE OU #2-03"
  type: "qube-ou-b"
  address: "10.1.0.7"
  adapter: "500202A504AAA"
U10B:
  name: "QuBE OU #2-06"
  type: "qube-ou-b"
  address: "10.1.0.10"
  adapter: "500202A503YAA"
U13B:
  name: "QuBE OU #2-09"
  type: "qube-ou-b"
  address: "10.1.0.13"
  adapter: "500202A507XAA"
U15A:
  name: "QuBE OU #2-11"
  type: "qube-ou-a"
  address: "10.1.0.15"
  adapter: "500202A501OAA"
R19A:
  name: "QuBE Riken #1-01"
  type: "qube-riken-a"
  address: "10.1.0.19"
  adapter: "500202A502CAA"
R20A:
  name: "QuBE Riken #1-02"
  type: "qube-riken-a"
  address: "10.1.0.20"
  adapter: "500202A500IAA"
R21B:
  name: "QuBE Riken #1-03"
  type: "qube-riken-b"
  address: "10.1.0.21"
  adapter: "500202A501DAA"
R28A:
  name: "QuBE Riken #1-10"
  type: "qube-riken-a"
  address: "10.1.0.28"
  adapter: "500202A504RAA"
R31A:
  name: "QuBE OU #3-01"
  type: "qube-riken-a"
  address: "10.1.0.31"
  adapter: "500202A505PAA"
Q73A:
  name: "QuEL-1 #5-01"
  type: "quel1-a"
  address: "10.1.0.73"
  adapter: "500202A50TAAA"
