64Q:
  - mux: 0
    ctrl: [R21B-5, R21B-0, R21B-2, R21B-6]
    read_out: R19A-13
    read_in: R19A-12
  - mux: 3
    ctrl: [R21B-7, R21B-11, R21B-13, R21B-8]
    read_out: Q2A-8
    read_in: Q2A-7
  - mux: 4
    ctrl: [R19A-5, R19A-6, R19A-7, R19A-8]
    read_out: R19A-0
    read_in: R19A-1
  - mux: 5
    ctrl: [Q2A-2, Q2A-4, Q2A-9, Q2A-11]
    read_out: Q2A-1
    read_in: Q2A-0
  - mux: 8
    ctrl: [U10B-5, U10B-0, U10B-2, U10B-6]
    read_out: R31A-13
    read_in: R31A-12
  - mux: 9
    ctrl: [R31A-5, R31A-6, R31A-7, R31A-8]
    read_out: R31A-0
    read_in: R31A-1
  - mux: 10
    ctrl: [U7B-5, U7B-0, U7B-2, U7B-6]
    read_out: Q73A-8
    read_in: Q73A-7
  - mux: 11
    ctrl: [U7B-7, U7B-11, U7B-13, U7B-8]
    read_out: R28A-13
    read_in: R28A-12
  - mux: 13
    ctrl: [Q73A-2, Q73A-4, Q73A-9, Q73A-11]
    read_out: Q73A-1
    read_in: Q73A-0
  - mux: 15
    ctrl: [R28A-5, R28A-6, R28A-7, R28A-8]
    read_out: R28A-0
    read_in: R28A-1

16Q:
  - mux: 0
    ctrl: [U13B-5, U13B-0, U13B-2, U13B-6]
    read_out: U15A-13
    read_in: U15A-12
  - mux: 1
    ctrl: [U15A-5, U15A-6, U15A-7, U15A-8]
    read_out: U15A-0
    read_in: U15A-1
  - mux: 2
    ctrl: [R20A-5, R20A-6, R20A-7, R20A-8]
    read_out: R20A-0
    read_in: R20A-1
  - mux: 3
    ctrl: [U13B-7, U13B-11, U13B-13, U13B-8]
    read_out: R20A-13
    read_in: R20A-12
