[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qubex"
dynamic = ["version"]
requires-python = ">=3.9"
authors = [{ name = "Akinori MACHINO" }]
description = "Quantum Experiment Tools using QuBE"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "httpx ~= 0.0",
    "jsonpickle ~= 3.0",
    "jupyter ~= 1.0",
    "matplotlib ~= 3.0",
    "numpy ~= 1.0",
    "pip == 24.0",
    "plotly ~= 5.0",
    "pydantic ~= 2.0",
    "pyyaml ~= 6.0",
    "qctrl-visualizer ~= 8.0",
    "qutip ~= 5.0",
    "rich ~= 13.0",
    "scikit-learn ~= 1.0",
    "scipy ~= 1.0",
    "tqdm ~= 4.0",
]

[project.optional-dependencies]
backend = [
    "qubecalib @ git+https://github.com/qiqb-osaka/qube-calib.git@3_1_0_RC",
]

[tool.setuptools.dynamic]
version = { attr = "qubex.version.get_version" }

[tool.setuptools.package-data]
qubex = ["py.typed", "clifford/*.json"]

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"

[tool.mypy]
ignore_missing_imports = true

[tool.ruff.lint]
ignore = ["E731"]
