[project]
name = "qubex"
version = "0.5.0"
requires-python = ">=3.9"
dependencies = [
    "jupyter",
    "matplotlib",
    "numpy",
    "scipy",
    "scikit-learn",
    "qutip",
    "pydantic",
    "qctrl-visualizer",
]
